# ── Module resource variables ─────────────────────────────────────────────────
# Used by Terraform to create the Temporal Cloud namespace and register
# the CA certificate that authorises worker mTLS connections.

variable "temporal_cloud_api_key" {
  description = "Temporal Cloud API key for authenticating the Terraform provider"
  type        = string
  sensitive   = true
}

variable "namespace_name" {
  description = "Name of the Temporal Cloud namespace to create"
  type        = string
  default     = "temporal-vault-demo"
}

variable "namespace_region" {
  description = "Temporal Cloud region (e.g. aws-us-east-1)"
  type        = string
  default     = "aws-us-east-1"
}

variable "retention_days" {
  description = "Workflow history retention period in days"
  type        = number
  default     = 7
}

# ── TLS certificate variables ─────────────────────────────────────────────────
# Controls the self-signed CA and client certificate generated by the tls
# provider. The CA is registered with Temporal Cloud; the client cert/key
# are written to the EC2 instance so the worker can authenticate via mTLS.

variable "cert_org" {
  description = "Organisation name embedded in the generated certificates"
  type        = string
  default     = "temporal-vault-demo"
}

variable "cert_validity_hours" {
  description = "Validity period for generated certificates in hours (default 1 year)"
  type        = number
  default     = 8760
}
